modLoader = "javafml"
loaderVersion = "[35,)"
license = "MIT"

[[mods]]
modId = "reputation"
version = "${version}"
displayName = "Reputation"
displayURL="https://github.com/TexTrueStudio/Reputation-Backport" #optional
credits="The_Computerizer" #optional
authors="ThinkingStudio" #optional
description = '''

'''

[[dependencies.reputation]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reputation]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
